CardanoCSL.hs
CardanoLib.hs
CardanoTW.hs
compileconfig.nix
config.nix
default.nix
deployments/cardano.nix

CardanoCSL: fetch node0 public IP

---

.travis.yml
deployments/cardano.nix
deployments/infrastructure.nix
deployments/timewarp.nix
lib.nix
modules/cardano-node.nix
modules/common.nix
modules/hydra-master.nix
modules/hydra-slave.nix

WIP: hydra and cardano deployments

---

.travis.yml
CardanoCSL.hs
README.md
deployments/cardano-explorer-ec2.nix
deployments/cardano-explorer-vbox.nix
deployments/cardano-explorer.nix
deployments/cardano.nix
deployments/infrastructure.nix
deployments/timewarp.nix
lib.nix
modules/amazon-base.nix
modules/cardano-node.nix
modules/common.nix
modules/report-server.nix
pkgs/cardano-sl-explorer.nix
pkgs/generate.sh
scripts/generate-explorer-frontend.sh

Following change have been implemented to support this:
- we're transitioning to IOHK AWS credentials
- EC2 specific settings have been extracted into separate module
- VirtualBox support for local testing
- explorer node has static dht/ip mappings specified
- ability to auto start the executable

[CSLA-61] explorer node

---

modules/cardano-node.nix
pkgs/cardano-sl.nix
pkgs/generate.sh
pkgs/kademlia.nix
pkgs/network-transport-tcp.nix
pkgs/time-warp-nt.nix

`master-testnet` is actually the branch that was deployed, but I cherry-picked the latest commit (871bdb2a45e0fe7d2fb4d4857625803ca65842f2) from it.
My understanding is necessary portions from the preceding commit in that branch (3abca38d0e098d03ebbce21d2e2fc76b8fd81aa8) have already been merged.

Latest testnet hotfix deployment

---

deployments/cardano-prod.nix
deployments/cardano.nix

This also includes two fixes already deployed to testnet. Need to get them in ASAP for any further deploys.

[DEVOPS-67] disable burst limiting of logs

---

pkgs/cardano-sl.json
pkgs/generate.sh
pkgs/time-warp-nt.nix

https://github.com/input-output-hk/cardano-sl/compare/be7cb65f71e7bd5b34778652009469c4513ecb79...cardano-sl-0.4

[DEVOPS-82] Bump cardano-sl to 0.4.4

---

deployments/infrastructure.nix
deployments/timewarp.nix
modules/cardano-explorer.nix
modules/cardano-node.nix
modules/common.nix
modules/report-server.nix
modules/timewarp-node.nix

Issue: https://issues.serokell.io/issue/DEVOPS-53

[DEVOPS-53] enable firewall on nodes

---

modules/cardano-node.nix

also change it from a cronjob to a systemd timer
and you can select between hourly and daily, with an adjustable rolling-restart gap

[DEVOPS-111]: change the restart timer to daily

---

jobsets/default.nix
jobsets/spec.json
modules/hydra-master.nix
nixpkgs-src.json
shell.nix

`../static/github_token` must contain a string similiar to `token 725c542324ffef7e915697bf445759c31dc0eaba`
i obtained mine by going to https://github.com/settings/tokens and creating a token with `repo:status`, but other methods listed on https://developer.github.com/v3/#authentication can also be used

Devops 171 hydra prs

---

production-infra.yaml

Deploy:
1. Created new user `iohk-devops` for Hydra PR building
2. Bumped nixpkgs in `production-infra.yaml`
3. `./Infra.hs deploy -c production-infra.yaml`

Deploy infra to production

---

jobsets/default.nix

requires: https://github.com/input-output-hk/cardano-sl/pull/1046
this enables building every PR on cardano-sl
note: any PR started before 1046 got merged will fail to eval until it is rebased

build all cardano PR's

---

default.nix
iohk/NixOps.hs
iohk/iohk-ops.hs
lib.nix
modules/common.nix
shell.nix

This makes two changes (so far):
1. add nixpkgs commit to `NixopsConfig` and carry it from/to `config.yaml`
2. make the `template` command fill in its value from `nixpkgs-src.json`
TODO:
1. [ ] figure out how to make `iohk-ops deploy`/etc. respect that commit id value
- hypothesis:  overwrite `nixpkgs-src.json`? (_/me laughs madly_)

[DEVOPS-190] nixpkgs commit in config.yaml

---

jobsets/default.nix
jobsets/simple-pr-dummy.json

add a jobset to build cardano-sl master
add a dummy PR json to aid in testing

rename the hydra jobsets

---

iohk/NixOps.hs
modules/cardano-node-prod.nix
production-testnet.yaml

This one cherry-picks some commits from https://github.com/input-output-hk/iohk-ops/pull/96/commits
- change from Serokell to IOHK AWS account for development deploys
- set startTime for testnet 0.5
- add testnet deployment yaml
The rest of the changes shouldn't be in master :)

Misc domen

---

default.nix
nixpkgs-src.json
production-infra.yaml

Already deployed to production infra.

[DEVOPS-270] Bump nixpkgs to fix auto-resizing aws volume

---

topology-staging.yaml

I have added a new, tentative configuration for staging which exploits unprivileged relays.
I'm not 100% sure if I've got the dynamic routes right, which I guess @dcoutts could approve or reject.

Update topology file with latest unprivileged relay feature

---

modules/hydra-slave.nix

the old config would keep 32gig free, and check once a day
this commit makes it check hourly

hydra entirely ran out of space today

---

.gitignore
.travis.yml
scripts/travis.sh

https://issues.serokell.io/issue/DEVOPS-338

[DEVOPS-338] More complete travis sh

---

deployments/infrastructure-env-production.nix
deployments/infrastructure-target-aws.nix
deployments/infrastructure.nix
modules/amazon-base.nix
production-infra.yaml
topology-mainnet-infra.yaml

Deploying deployer

---

topology-production.yaml

`c-a-1` became `c-d-1` (new region, now 4)
`c-a-2` became `c-a-1`
`c-a-3` became `c-a-2`

[DEVOPS-164] Prepare mainnet topology

---

iohk/NixOps.hs

`--build-only` was preventing `GC_INITIAL_HEAL_SIZE` from being set.

[DEVOPS-378] setenv

---

modules/staging.nix

related: https://github.com/NixOS/nixpkgs/pull/30141

temporarily fix datadog tags until fix is merged upstream

---

modules/production.nix

See https://github.com/input-output-hk/iohk-ops/commit/eda2e6bedbcfb6087613b21e946da15a8cf2e518

Apply same fix that was verified in staging

---

iohk/NixOps.hs
iohk/iohk-ops.hs

Same as previous PR, but with:
- issue id added to the commits
- pointing to correct branch

Devops 377 reallocate core ips

---

iohk/NixOps.hs

devops-411:  iohk-ops deploy:  reduce initial GC heap to 6GiB

---

deployments/cardano-explorer-env-production.nix
deployments/cardano-nodes-env-production.nix
deployments/cardano-nodes-env-staging.nix
modules/datadog-monitors.nix

[DEVOPS-451] Update DataDog monitors to reflect manual fixes.

---

iohk/NixOps.hs
modules/datadog-monitors.nix

Minor issues that came up during the mainnet update deployment. They were already applied manually, but need to be merged.

[DEVOPS-461] Fixes applied during mainnet update

---

cardano-sl-src.json
deployments/report-server-bucket-storage.nix
iohk/default.nix
modules/datadog-monitors.nix

The branch is not pretty, and it deserved dis-entangling before PR creation.
..but we also want to record what was deployed.

release/mainnet 2017-11-01

---

.gitignore
cardano-sl-src.json
iohk/Constants.hs
iohk/Nix.hs
iohk/NixOps.hs
iohk/Topology.hs
iohk/Types.hs
iohk/Utils.hs
iohk/iohk-ops.hs
modules/development.nix
scripts/travis.sh
topology-development.yaml

- dev-env key generation
- DNS provisioning in the `aws.iohkdev.io` domain

Devops 157 support developers

---

iohk/Constants.hs
iohk/NixOps.hs
iohk/Types.hs
iohk/iohk-ops.hs

This brings back the previously implemented journald log subsetting in `iohk-ops get-journals`.

[CSL-1885] journal subsetting

---

globals.nix
modules/cardano-production.nix
topology-production.yaml

1. define four more public relays -- two in Tokyo and two in Singapore
1. set the public relay instance types to `m4.large`

[DEVOPS-538] relay instances

---

relay-batch-4.yaml
topology-bulk4.yaml

adding another set of 20 relays

the 40s relays

---

.gitignore
default.nix
nixpkgs-src.json
scripts/ci.sh
terraform/README.md
terraform/appveyor-s3-cache/README.md
terraform/appveyor-s3-cache/main.tf
terraform/modules/ci-cache-s3/main.tf
terraform/modules/ci-cache-s3/output.tf
terraform/modules/ci-cache-s3/variables.tf
terraform/modules/s3-full-access-policy/main.tf

Required for https://github.com/input-output-hk/cardano-sl/pull/2166

[DEVOPS-61] Add terraform to bootstrap cache-s3 bucket

---

static/csl-logging.yaml

1. Make it work with newest log-warper (used in latest cardano-sl).
2. Make it print all logs to node.log, remove obsolete stuff.

[CSL-2186] Update csl-logging.yaml config

---

cardano-sl-src.json
default.nix
modules/cardano-service.nix

These changes fix the cluster deploying, specifically the node binary and configuration file paths.

[CSL-1983] Fix testnet deploying

---

default.nix
terraform/README.md
terraform/appveyor-deploy-s3/README.md
terraform/appveyor-deploy-s3/bucket-index.html
terraform/appveyor-deploy-s3/main.tf
terraform/appveyor-s3-cache/README.md
terraform/modules/ci-deploy-s3/main.tf
terraform/modules/ci-deploy-s3/output.tf
terraform/modules/ci-deploy-s3/variables.tf

Infrastructure setup for input-output-hk/daedalus#717

[DEVOPS-653] terraform: add snippet for appveyor deploy bucket

---

cardano-sl-src.json
deployments/report-server-env-production.nix
deployments/report-server-env-staging.nix
deployments/report-server.nix
iohk/iohk-ops.hs
modules/report-server.nix

Works in a development cluster.

[DEVOPS-683] Add zendesk token to report-server

---

default.nix
deployments/infrastructure-env-production.nix
deployments/infrastructure-env-staging.nix
deployments/infrastructure-target-aws.nix
deployments/infrastructure.nix
deployments/keypairs.nix
iohk/Constants.hs
iohk/NixOps.hs
iohk/default.nix
iohk/iohk-ops.hs
mainnet-infra.yaml
scripts/ci.sh
staging-infra.yaml

This is a sister PR to https://github.com/input-output-hk/iohk-ops/pull/191

[DEVOPS-382] staging infra master

---

jobsets/default.nix

also allow hydra to opt-out of cardano PR's (they default to on)
https://hydra.angeldsis.com/project/iohk-auto shows a preview of what hydra will do with these changes

add support for daedalus building on hydra, including PR's

---

cardano-sl-src.json

[DEVOPS-692] Update cardano-report-server to 0.4.9

---

cardano-sl-src.json

https://github.com/input-output-hk/cardano-sl/commit/0951cf307ce9af341a5128acd8df30b5393b36ab

Bump cardanosl revision to 0951cf307ce9af341a5128acd8df30b5393b36ab

---

deployments/infrastructure-env-production.nix
iohk/Constants.hs
modules/hydra-master.nix
production-infra.yaml

Hotfix will be merged into `develop` after approval.

[DEVOPS-166] Update hydra build slave IPs and route 53 key for hydra

---

Benchmarks.md
collect-data.nix
run-bench.nix

Updated nix script so as to stop edge nodes' cluster before and after a run.
Number of edge nodes (wallets) to be used added as a parameter in the appropriate scripts.

[PB-51] Creating nix scripts instead of one bash script updated

---

collect-data.nix
modules/cardano-service.nix
run-bench.nix

Policy files will change in `modules/cardano-sevice.nix` file.
Parameters of nix scripts  are recorded in `run-bench-args.txt` and `collect-data-args.txt`

[PB-51] Added option for policy files and output parameters of nix scripts

---

default.nix
iohk/NixOps.hs
iohk/UpdateLogic.hs
iohk/UpdateProposal.hs
iohk/Utils.hs

This is the scripting for running gpg and uploading the signatures to S3.
@deepfire is working on signing key management.
It's based off PR #317, so that needs to be merged first.

[DEVOPS-710] iohk-ops update-proposal: add installer signatures

---

default.nix
terraform/default.nix
terraform/devops-839-hermes/README.md
terraform/devops-839-hermes/aws.tf
terraform/devops-839-hermes/configuration.nix
terraform/devops-839-hermes/main.tf
terraform/devops-839-hermes/outside.tf
terraform/devops-839-hermes/variables.tf
terraform/shell.nix

Sets up a temporary NixOS machine for development purposes.

[DEVOPS-839] Terraform for project hermes dev machine

---

iohk/NixOps.hs

Not exactly what was envisioned, but in the same ballpark.

DEVOPS-193:  cardano-node-commit-monitor

---

jobsets/default.nix

See also: input-output-hk/cardano-sl#3544.

[DEVOPS-1032] hydra: Build cardano-sl PRs with optimization disabled

---

deployments/bors-ng.nix
deployments/infrastructure-env-production.nix
deployments/infrastructure-env-staging.nix
deployments/infrastructure-target-aws.nix
deployments/infrastructure.nix
iohk/iohk-ops.hs
modules/bors-ng-service.nix

Adds an instance to the infra deployment for bors-ng.
The NixOS service was tested in a nixops virtualbox deployment with a github application under my account.

[DEVOPS-1044] infra: add bors-ng instance

---

shell.nix

Dug up my old branch with bash completion enabled because it can be part of some general work to improve the iohk-ops CLI.

[DEVOPS-1066] Add bash completion to `io` command

---

nix-darwin/NukeNix.hs
nix-darwin/PrepareDarwin.hs
nix-darwin/RewriteLibs.hs
nix-darwin/default.nix
nix-darwin/deploy-darwin.hs
nix-darwin/everything.hs
nix-darwin/patch-prepare.hs

I'm using this locally on my home network to manage my macs and I've made some improvements I thought we might want in iohk-ops.

[DEVOPS-859] nix-darwin improvements

---

default.nix

https://github.com/input-output-hk/nixops/tree/iohk

[DEVOPS-1076] Use input-output-hk/nixops fork

---

jobsets/default.nix

The `no-opt-cardano-sl` jobset builds without optimization, so that PR builds based on `develop` will be able to use prebuilt packages.
The jobset name starts with `no-opt` so that it's not picked up by the Hydra github status plugin.
```
nix-build jobsets/default.nix -A jobsets -o spec.json
jq '.["cardano-sl"]' < spec.json
jq '.["no-opt-cardano-sl"]' < spec.json
jq '.["cardano-sl-pr-42"]' < spec.json
```

[DEVOPS-1032] jobsets: extra jobset to build cardano-sl develop branch without optimization

---

.gitignore
docs/Daedalus-Installer-Update-Procedure.md
docs/iohk-ops-reference.md
iohk/common/UpdateLogic.hs
modules/buildkite-agent.nix
scripts/ci.sh

These are things I noticed when doing the staging update proposal today.

[DEVOPS-998] Misc fixes resulting from staging update proposal

---

modules/buildkite-agent.nix

https://docs.haskellstack.org/en/stable/yaml_configuration/#non-project-specific-config
https://docs.haskellstack.org/en/stable/nix_integration/#configuration

[DEVOPS-1049] buildkite agents: add /etc/stack/config.yaml

---

benchmarks/Benchmarks.md
benchmarks/scripts/collect-data.nix
benchmarks/scripts/plots.r
benchmarks/scripts/run-bench.nix
iohk/common/NixOps.hs
static/txgen-logging-warnonly.yaml
static/txgen-logging.yaml

Adapt code and documentation to the new logging and to changes made in master.

[CBR-275] Adapt to new logging

---

modules/cardano-faucet-module.nix
modules/cardano-faucet.nix
testnet.yaml

Minor fixes to catch up with changes made elsewhere.

Testnet fixes

---

docs/bors.md
jobsets/default.nix

Turns out some deployment docs would be helpful.

[DEVOPS-1028] Add Bors for cardano-sl and docs

---

cardano-sl-src.json

Preparing for a redeploy of staging.

[DEVOPS-1140] Bump cardano-sl to latest release/2.0.0

---

lib/ssh-keys.nix

Added public SSH key for Charles Morgan, Director of CyberSecurity

Added public key for Charles Morgan

---

cardano-sl-src.json

[DEVOPS-1116] Bump cardano-sl to latest release/2.0.0

---

docs/Daedalus-Installer-Update-Procedure.md
iohk/common/UpdateProposal.hs
iohk/test/UpdateProposalSpec.hs

Linux Daedalus installers will be proposed on mainnet from now on.

[DEVOPS-1189] io update-proposal submit: include linux by default

---

jobsets/default.nix

tested with
```
jq . < $(nix-build --no-out-link jobsets/default.nix)
```

jobset: add iohk-nix

---

jobsets/default.nix
modules/hydra-master-main.nix

Let me know if there are any other places that I need to change things!

Update cardano-chain to cardano-ledger

---

windows/iohk-setup.ps1

A script for setting up windows to build cardano-sl.
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1168

[DEVOPS-1168] Add Windows dev environment for cardano-sl

---

jobsets/default.nix

jobsets | cardano 3.0.1

---

gac.sh

We need to load the configuration file for some operations overrides.
We are moving all the configuration parsing/reading related logic into
a proper function. This `load_config` option will be in scope for
the overrides.
Note to @deepfire : I've tested that on a test cluster. That said, there's no rush, it's not a blocker. I can work on my branch. Enjoy your summit :)

GAC | Move configuration to its own function.

---

deployments/configurator.nix
deployments/global.nix
deployments/infrastructure-env-production.nix
deployments/infrastructure-target-aws.nix
deployments/infrastructure.nix
deployments/monitoring-aws.nix
deployments/monitoring-env-devops.nix
deployments/monitoring-env-production.nix
deployments/monitoring-env-staging.nix
deployments/monitoring.nix
deployments/security-groups.nix
deployments/security-groups/allow-deployer-ssh.nix
iohk/common/Constants.hs
lib.nix
modules/devops.nix
modules/gen-wireguard-keys.nix
modules/hydra-fork.nix
modules/hydra-master-common.nix
modules/hydra-master-main.nix
modules/hydra-master-mantis.nix
modules/monitoring-exporters.nix
modules/monitoring-services.nix
modules/production.nix
modules/staging.nix
modules/test-hydra-locally.nix
modules/testnet.nix
nixpkgs-src.json
scripts/ci.sh

Jal infra monitoring

---

deployments/cardano-nodes-env-production.nix
deployments/global.nix
deployments/monitoring-env-production.nix
deployments/monitoring.nix
deployments/security-groups/allow-monitoring-collection.nix
modules/common.nix
modules/monitoring-exporters.nix
modules/monitoring-services.nix

clean up various other monitoring code

add node type to prometheus tags

---

jobsets/default.nix
jobsets/spec.json
modules/hydra-master-main.nix

Corresponding PR is input-output-hk/cardano-node#10
Tested with:
```
jq . < $(nix-build --no-out-link jobsets/default.nix)
```

jobsets: Add cardano-node and cardano-base

---

deployments/infrastructure-env-production.nix
modules/exchange-monitor/exchange-monitor.py

Adding monitoring for bithumb

---

deployments/infrastructure-env-production.nix
modules/exchange-monitor/exchange-monitor.py

Exchange monitoring

---

modules/monitoring-services.nix

Increased to 0.500
Triggered by PD #8323

Increased node_time_unsync threshold

---

default.nix
iohk/amazonka-content-length.patch
iohk/common/Buildkite/API.hs
iohk/common/UpdateLogic.hs

This adds the buildkite and AWS S3 fixes to master for update-proposal tooling.

Update proposal fixes

---

nix-darwin/modules/double-builder-gc.nix

Some tweaks made by others in the team that had to be stashed due to clashes with PR #702 and I'm now pushing back up to master.
@iohk-devops

Fine tuning garbage collection for Darwin builds

---

modules/mac-host-common.nix

ZFS volume name changes made by others in the team that had to be stashed due to clashes with PR #702 and I'm now pushing back up to master.
@iohk-devops

Changed ZFS volume names to reflect size

---

modules/auto-gc.nix

Some tweaks made by others in the team that had to be stashed due to clashes with PR #702 and I'm now pushing back up to master.
@iohk-devops

Fine tuning garbage collection configuration
