- CardanoCSL.hs
- modules/cardano-node.nix
In order to avoid high load during deployment, start cardano-node only during experiments.
> Manually start cardano-node

- CardanoCSL.hs
- CardanoLib.hs
- Infra.hs
- NixOps.hs
- TimeWarp.hs
Compiles and did basic testing.
Run with `$ ./CardanoCSL.hs -c csl-production.yaml runexperiment`
```
$ cat csl-production.yaml 
deploymentName: cardano-production
nixPath: ~/
deploymentFiles:
- deployments/cardano.nix
nixopsExecutable: /home/production/nixops/result/bin/nixops
```
```
$ cat tw-production.yaml
deploymentName: timewarp-production
nixPath: ~/
deploymentFiles:
- deployments/timewarp.nix
nixopsExecutable: /home/production/nixops/result/bin/nixops
```
**Each deployment should have a unique `deploymentName` not to interfere.**
> [CSL-457] Use configuration file for deployments

- .travis.yml
- default.nix
- modules/cardano-node.nix
- pkgs/acid-state.nix
- pkgs/cardano-crypto.nix
- pkgs/cardano-report-server.nix
- pkgs/cardano-sl-explorer.nix
- pkgs/cardano-sl.nix
- pkgs/cryptonite.nix
- pkgs/derive.nix
- pkgs/ed25519.nix
- pkgs/generate.sh
- pkgs/kademlia.nix
- pkgs/log-warper.nix
- pkgs/network-transport-tcp.nix
- pkgs/network-transport.nix
- pkgs/plutus-prototype.nix
- pkgs/rocksdb-haskell.nix
- pkgs/serokell-util.nix
- pkgs/time-warp-nt.nix
- pkgs/universum.nix
- srk-nixpkgs.nix
Previously we were using `haskellPackageGen`, which generates packages
from their source, but this is using import-from-derivation
feature in Nix, meaning that evaluation and realization mix and match.
It was especially problematic for Hydra as it was building packages during evaluation and it timed out after 1h.
Now we have a `pkgs/generate.sh` file that also doesn't need to specify
sha256 so bumping packages is easier.
Soon that should be all automated using `stack2nix`.
> Refactor Nix package generation

- deployments/cardano-prod.nix
- deployments/infrastructure.nix
- modules/datadog.nix
TODO:
- bump nixpkgs to 7ad99e9fc8c1977f4d51ba8531386fce7276d300
- add `deployments/cardano-prod.nix` to `deploymentFiles` section of yaml
> [DEVOPS-3] Setup datadog for prod nodes and hydra/deployer

- deployments/cardano-prod.nix
- deployments/infrastructure.nix
- modules/papertrail.nix
Depends on https://github.com/input-output-hk/iohk-nixops/pull/17 for separating prod/staging.
Tested on cardano-deployer it works very nice.
> [DEVOPS-1] Setup papertrail

- CardanoCSL.hs
- README.md
- config.nix
- deployments/cardano.nix
- deployments/infrastructure.nix
- deployments/timewarp.nix
- lib.nix
- modules/amazon-base.nix
- modules/amis.nix
- modules/cardano-node.nix
- scripts/create-amis.sh
- scripts/upload_keys.sh
Deployment was carried out using https://github.com/input-output-hk/internal-documentation/wiki/testnet-deploy
- deploy nodes over 7 availability zones
- periodically restart nodes due to stability issues
- regenerate amis for NixOS 17.03
- add a script to upload keys
- bump system start
- initial disk size is 700G
> [DEVOPS-41] Changes needed for testnet deploy

- deployments/cardano-explorer-staging.nix
- deployments/cardano.nix
- modules/cardano-explorer.nix
- pkgs/cardano-sl-explorer.nix
- pkgs/generate.sh
This is not ideal, as it duplicates things. It will be addressed in DEVOPS-37.
https://cardano-explorer-dev.iohk.io/
Instructions: https://input-output-rnd.slack.com/archives/C3NJV7ADQ/p1493300293365767
> [DEVOPS-86] Explorer staging deployment

- deployments/cardano-prod.nix
This requires upstream changes in nixpkgs: https://github.com/NixOS/nixpkgs/pull/25288
A single node using process monitoring is running at `[staging@cardano-deployer:~/devops-45-monitor-cardano-node-process]$ nixops ssh -d devops-41 node0`
> [DEVOPS-45] Monitor cardano-node process on datadog

- CardanoCSL.hs
This executes on the code modification part of https://issues.serokell.io/issue/DEVOPS-60
@domenkozar, I've been operating under assumption that to this day this tool was used manually, since there are no mentions of `generate-ipdht` neither in `iohk-nixops`, nor in `daedalus` or `cardano-sl`.
One consequence is that there is no integration to update, so this is actually a very very trivial change AIUI.
Please correct me if I'm wrong!
> [DEVOPS-60]  Redirect output of CardanoCSL.hs/generate-ipdht from file to stdout

- modules/cardano-explorer.nix
This needs a counterpart fix in explorer not to set port when ran in production.
I have deployed the change to https://explorer.iohkdev.io/ and it works
> [DEVOPS-98] Proxy socket.io through nginx to fix cloudflare

- .travis.yml
- modules/cardano-node-aws.nix
- modules/common.nix
Rebased on top of https://github.com/input-output-hk/iohk-nixops/pull/47
Tested via small node deployment, the key is uploaded and copied to `/var/lib/cardano-node/keyX.sk`
TODO:
> [DEVOPS-25] provision node secret key

- .gitignore
- .travis.yml
- deployments/infrastructure-target-aws.nix
- deployments/infrastructure.nix
- lib.nix
- modules/amazon-base.nix
- modules/cardano-node-aws.nix
- set ami only for cardano nodes
- configure tarsnap backups for cardano-deployer
- bump nixops to be able to set `destDir` to avoid non-persistent key storage
> [DEVOPS-2] tarsnap: backup deployer

- Infra.hs
- deployments/infrastructure-target-aws.nix
- `nixops modify -d iohk-infra deployments/infrastructure{,-target-aws,-env-production}.nix deployments/keypairs.nix`
- change `nixops` in `Infra.hs` to `/nix/store/4d01h8i6j33yn3a69wraddfl1ily0ii9-nixops-2017-05-22/bin/nixops`
- `nix-shell -p tarsnap --run "tarsnap-keygen --keyfile tarsnap-cardano-deployer.secret --machine cardano-deployer --user tarsnap@iohk.io"`
- `./Infra.hs deploy`
> Deploy sprint #4 to infrastructure

- modules/cardano-node.nix
Tested using 1 node and:
```
systemctl start cardano-node
systemctl status cardano-node
kill 1849
systemctl status cardano-node
systemctl status cardano-node
```
> [DEVOPS-46] Restart cardano-node a few times

- deployments/keypairs.nix
- lib.nix
- modules/amazon-base.nix
- modules/cardano-node-aws.nix
This also changes `enableP2P` to be respected only in development since it doesn't make sense in production.
TODO:
> [DEVOPS-58] Automate creating security groups

- CardanoCSL.hs
- Infra.hs
- NixOps.hs
- TimeWarp.hs
This is to:
1. allow `--debug` passed to most `nixops` commands
2. facilitate easier future options definitions
> [DEVOPS-142]  Implement a global --debug flag for all deployment scripts

- deployments/cardano-nodes-env-production.nix
- deployments/cardano-nodes-env-staging.nix
- modules/datadog-monitors.nix
- Fix default monitor scopes so they use the appropriate DataDog tag.
- Increase consecutive failure thresholds for process monitor. When it
was set to 1 consecutive failure, scheduled restarts could cause
false alarms.
- Add `pagerDutyPolicy` so urgency can be changed per deployment
environment.
> [DEVOPS-108] Improve DataDog monitors.

- tests/simple-node-nixops.nix
- tests/simple-node.nix
https://hydra.iohk.io/jobset/serokell/cardano-sl-staging#tabs-errors
```
in job ‘tests.simpleNode.x86_64-linux’:
Failed assertions:
- services.cardano-node.initialPeers must be set, a node needs at least one initial peer (testIndex: 0)
```
> fix hydra eval of the tests

- jobsets/default.nix
when jobsets/default.nix generates a jobset for a PR, it won't know the correct nixpkgs to use
this patch makes the jobset fetch its own nixpkgs
> lock nixpkgs for pr building

- modules/cardano-node-aws.nix
- modules/cardano-node.nix
This wires things up so that https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1497925423905&to_ts=1497929023905&tile_size=m&exp_metric=rts.gc.gc_wall_ms&exp_scope=&exp_agg=avg&exp_row_type=metric can be observed : -)
> [DEVOPS-74]  Deploy EKG->statsd->Datadog stats

- .travis.yml
- fetch-nixpkgs.nix
- jobsets/cardano.nix
- jobsets/default.nix
- lib.nix
- modules/common.nix
- pkgs/generate.sh
- scripts/find-all-revisions.sh
- scripts/generate-explorer-frontend.sh
- scripts/set_nixpath.sh
- shell.nix
- tests/default.nix
most parts of the project now obey nixpkgs-src.json
the #!nix-shell stuff cant be configured to read from a file, so they now expect the user to `source scripts/set_nixpath.sh` before being ran, that will probably change after DEVOPS-22
still needs a travis check to ensure no new paths get added
> [DEVOPS-123] nixpkgs unification

- modules/cardano-node.nix
nixos can already create a script to do what cardano-node was doing, and it makes the logs more readable as well
```
Jun 29 13:04:54 amd-nixos kvz0yn3vgy23vb79d3f5j2v2wbqnkmp9-cardano-node.sh[26368]: [node:DEBUG:ThreadId 34] [2017-06-29 13:04:54 ADT] waiting for [] outbound inbound
Jun 29 13:04:54 amd-nixos kvz0yn3vgy23vb79d3f5j2v2wbqnkmp9-cardano-node.sh[26368]: [*production*.transport:ERROR:ThreadId 18] [2017-06-29 13:04:54 ADT] Exception in tcp server: thread killed
Jun 29 13:04:54 amd-nixos systemd[1]: Stopped cardano node service.
Jun 29 13:04:55 amd-nixos systemd[1]: Started cardano node service.
Jun 29 13:04:55 amd-nixos cardano-node-start[10691]: [Attention] We are in PRODUCTION mode
Jun 29 13:04:55 amd-nixos cardano-node-start[10691]: [Attention] Web-mode is on
Jun 29 13:04:55 …
```
> optimize the systemd unit

- .travis.yml
- cardano-sl-explorer-src.json
- cardano-sl-src.json
- default.nix
- jobsets/cardano.nix
- pkgs/cardano-sl-explorer.nix
- pkgs/default.nix
- pkgs/generate.sh
- pkgs/stack2nix.nix
- scripts/check-stack2nix.sh
- shell.nix
- stack2nix-src.json
found an edgecase in testing this, updating `pkgs/default.nix` changes the build of stack2nix, and now travis cant use the cached copy, so it needs a PR built by hydra
> [DEVOPS-32] ensure pkgs/default.nix is up to date

- production-infra.yaml
Production infrastructure was re-deployed using the new `iohk-ops` tooling.
This PR records the actual config it was deployed with.
> [DEVOPS-22]  production-infra.yaml: change over to the new format

- iohk/default.nix
- scripts/aws.hs
- shell.nix
Tested on the `daedalus-installer-test` bucket.
https://issues.serokell.io/issue/DEVOPS-195#comment=96-5415
> [DEVOPS-194]  Fix scripts/aws.hs impurities:  make awscli specified as input

- cardano-sl-explorer-src.json
- cardano-sl-src.json
- pkgs/cardano-sl-explorer.nix
- pkgs/default.nix
Based on this https://github.com/input-output-hk/internal-documentation/wiki/Deploying-clusters-from-scratch#example used:
```
nix-shell -p nix-prefetch-scripts
$(nix-build -A iohk-ops)/bin/iohk-ops set-explorer-rev 26d1c096f9f9a4a46b731334ed4adb0fb260f6c7
$(nix-build -A iohk-ops)/bin/iohk-ops set-cardano-rev 97850b14ca8e6a4d0055e4f8a6a90380967263b0
./pkgs/generate.sh
```
> Bumped cardano/explorer

- pkgs/default.nix
- scripts/aws.hs
- scripts/stack.yaml
Test scenario:
```
[nix-shell:~/iohk]$ scripts/aws.hs s3 --bucket daedalus-travis-test set-daedalus-release-build
0.5.1994 0.5.2110.0 v9cnlytcf5my4g2u
Setting Daedalus release redirects to:
OS X:   https://s3.eu-central-1.amazonaws.com/daedalus-travis/Daedalus-installer-0.5.1994.pkg
Win64:  https://ci.appveyor.com/api/buildjobs/v9cnlytcf5my4g2u/artifacts/installers/daedalus-
win64-0.5.2110.0-installer.exe
============== Checking if OSX build URL is live:
Spider mode enabled. Check if remote file exists.
--2017-07-27 01:07:54--  https://s3.eu-central-1.amazonaws.com/daedalus-travis/Daedalus-install
er-0.5.1994.pkg
Resolving s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)... 52.219.72.32
Connecting to s3.eu-central-1.amazonaws.com …
```
> DEVOPS-218: make `scripts/aws.hs s3 set-daedalus-release-build` also provide version texts

- modules/cardano-node.nix
- tests/simple-node.nix
- virtualize Haswell instructions (including SSE3)
- use fixed pkgs, not the one provided by tests
> Fix SSE3 support in qemu

- modules/cardano-node-staging.nix
On staging we discovered this monitor picking up on false
positives. When `exact_match == False` the command's arguments are
included in the search, meaning `journalctl -f -u cardano-node` would
be a match. That triggers the monitor because the monitor expects
exactly 1 cardano-node process per node at any given moment.
Enabling `exact_match` means the comparison only involves the process'
name. Until we see false positives related to multiple concurrent
cardano-node processes, I'm not loosening the "exactly one match"
invariant.
> Use exact match on Datadog process monitor for "cardano_node"

- modules/hydra-master.nix
the first regex to match will take all jobs, and prevent any further
status entries from running
> fix github status plugin

- .travis.yml
- iohk/NixOps.hs
Sadly `--evaluate-only` doesn't evaluate each machine, so we have to use `--dry-run` for this. Waiting on CI to confirm.
> --evaluate-only -> --dry-run

- fetch-nixpkgs.nix
- lib.nix
- modules/common.nix
- nixpkgs-src.json
- scripts/set_nixpath.sh
this change allows the nix expressions to work with a blank NIX_PATH variable, so there is no chance for impurities to leak in
once tested under such a situation, it is safe to ignore NIX_PATH, and just leave it as-is on any system
todo:
> [DEVOPS-333] allow the nix expressions to work with a blank NIX_PATH

- modules/cardano-staging.nix
As explained in the ticket, I verified indentation is the source of the bug. This is a potential fix, although it still needs to be verified.
> [DEVOPS-341] Fix YAML indentation in nix file

- cardano-sl-src.json
- default.nix
- iohk/NixOps.hs
- modules/cardano-explorer.nix
- modules/cardano-service.nix
- modules/report-server.nix
- scripts/generate-explorer-frontend.sh
@deepfire this is counterpart to https://github.com/input-output-hk/cardano-sl/pull/1587/commits/c1005df36a0f873a3477cee7bf76e1057a2147d9 already in the upstream genesis brannch
As soon as we bump cardano-1.0 this will be needed (otherwise you'll get an error that `dconfig` input does not exist)
> [DEVOPS-354] Remove dconfig at compile time

- modules/datadog-monitors.nix
@jmitchell found some extra braces in the NTP monitor definition: https://input-output-rnd.slack.com/files/U3TUV412R/F79EMNXDX/monitor-scope-braces-before.png
No idea where those came from.
> Minor monitor fixes

- topology-production.yaml
- topology-staging.yaml
Given the proposed change for the DNS subscription worker https://github.com/input-output-hk/cardano-sl/pull/1668 to fix CSL-1700, we would need a topology update. Here is one to check carefully.
We changed the DNS policy mechanism so it behaves like the static routes with the outer list being multiple subscriptions (valency) and the inner being alternatives (backups) for each other.
The policy here is to use primary relays from the same region first, and for fallbacks use relays (ordered randomly) from other regions. The random ordering is to avoid concentrating load upon failures.
In addition, this includes the change to put all the unprivileged relays in Tokyo and Singapore (2 AZs in each region).
> topology update

- modules/datadog-monitors.nix
without this, datadog will average all drives together, and a system out of space will read as being 33% full
> fix the low-diskspace monitor to not average all drives together

- modules/cardano-service.nix
The time specs were tested using a local unit file/timer, but haven't been tested in this codebase yet. We need to deploy to staging, wait until at least one restart has occurred, and audit the `LAST` and `NEXT` of `systemctl list-timers` for correctness.
> [DEVOPS-406] Bump cardano restarts from 6h to 36h

- default.nix
- deployments/infrastructure.nix
- shell.nix
`nix-shell` will alias `io` to a binary build of `iohk-ops`
`nix-shell --arg io-dev-mode true` will alias `io` to an interpreted version
All variants source `iohk-ops` from the current definition.
> Devops 410 iohk ops

- default.nix
- deployments/report-server-bucket-storage.nix
- deployments/report-server-env-production.nix
- deployments/report-server-env-staging.nix
- deployments/report-server.nix
- globals.nix
- iohk/NixOps.hs
- iohk/iohk-ops.hs
- modules/report-server.nix
- scripts/travis.sh
- topology-mainnet-infra.yaml
currently, its enabled for both mainnet and staging, but it can easily be adjusted to target just one
due to boto2 in nixops, the bucket must be in a region that supports auth method version 2
the report-server ec2 is currently in frankfurt, so latency to the bucket may be high
>  [DEVOPS-455] implement S3 bucket storage for report-server logs

- iohk/Constants.hs
- iohk/iohk-ops.hs
This PR supports the final work for the upcoming developer cluster documentation (at https://github.com/input-output-hk/internal-documentation/wiki/Developer-clusters-HOWTO):
- `iohk-ops clone <CHECKOUT-NAME> [<IOHK-OPS-BRANCH>]`
> [DEVOPS-157]  iohk-ops clone:  specify the destination directory

- modules/datadog-monitors.nix
This will silence restart false alarms.
> [DEVOPS-602] Set degraded chain monitor to alert on 3min max.

- scripts/ci.sh
This is to re-enable logging of Nixops state cleanup, in context of DEVOPS-623 debugging.
> [DEVOPS-623]  ci:  trace cleanup

- README.md
- modules/common.nix
Have not been able to test this in a new developer cluster yet.
However there is a good chance it will work because the same config change worked in another NixOS setup.
> [DEVOPS-607] Disallow non-root set authorized_keys on all deployments

- modules/common.nix
nixops doesnt add its own keys to the nixos config, and assumes that the `~/.ssh/authorized_keys` setup by aws will remain in effect
> allow root to use ~/.ssh/authorized_keys

- iohk/iohk-ops.hs
This fixes DEVOPS-645:
```
nix-shell:~/testing-jumps]$ io new testing-jumps nodes
-- config.yaml is:
args:
configurationKey:
tag: NixStr
contents: devnet
EmurgoaccessKeyId:
tag: NixStr
contents: cardano-deployer
systemStart:
tag: NixInt
contents: 1517408907
CFaccessKeyId:
tag: NixStr
contents: cardano-deployer
IOHKaccessKeyId:
tag: NixStr
contents: cardano-deployer
gen-cmdline: new testing-jumps nodes
environment: Development
installer-bucket: default-bucket
topology: topology-development.yaml
name: testing-jumps
files:
- deployments/cardano-nodes-env-development.nix
- deployments/keypairs.nix
- deployments/cardano-nodes.nix
elements:
- Nodes
target: AWS
INFO: using default.nix expression for its definition of 'nixops'
INFO: nixops is …
```
> [DEVOPS-645]  iohk-ops:  update to the new cardano-keygen

- iohk/Buildkite/API.hs
- iohk/UpdateLogic.hs
- iohk/default.nix
- iohk/iohk-ops.cabal
- iohk/test/UpdateLogicSpec.hs
It gets the cardano revision from the buildkite cardano build.
Due to my mistake in #240 (DEVOPS-606), it was getting the most recent buildkite cardano build, rather than the one referred to in the build logs.
> [DEVOPS-666] find-installers: fix logic for getting cardano revision

- iohk/NixOps.hs
- iohk/Types.hs
- iohk/UpdateLogic.hs
- iohk/Utils.hs
If the daedalus build was in Travis, it was looking up the cardano build in Travis also. But cardano builds are now in Buildkite.
> [DEVOPS-665 DEVOPS-669] iohk-ops fixes for staging deploy

- deployments/report-server-env-production.nix
- deployments/report-server-env-staging.nix
- modules/report-server.nix
We have an `iohksupport.zendesk.com` account which will expire in 6 days.
Have tested this change in development cluster, with `report-server.zendesk` options temporarily enabled in that environment.
> [DEVOPS-683] report-server: Different Zendesk account for staging

- modules/report-server.nix
Turns out the `--zd-send-logs` option is wanted.
> [DEVOPS-683] report-server: Pass on logs to Zendesk by default

- deployments/infrastructure-target-aws.nix
- modules/hydra-slave.nix
Try to work around the semantic limitation of DD monitor definitions by grouping Hydra-related things with a tag instead.
> [DEVOPS-687] disc space mon

- deployments/infrastructure-target-aws.nix
Fix a minor threshold issue:
```
Traceback (most recent call last):
File "/nix/store/wm0jd92gb5vflky0bhkal5v9hvg4ap6a-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 984, in <module>
args.op()
File "/nix/store/wm0jd92gb5vflky0bhkal5v9hvg4ap6a-nixops-1.6pre0_abcdef/bin/.nixops-wrapped", line 407, in op_deploy
max_concurrent_activate=args.max_concurrent_activate)
File "/nix/store/wm0jd92gb5vflky0bhkal5v9hvg4ap6a-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1044, in deploy
self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
File "/nix/store/wm0jd92gb5vflky0bhkal5v9hvg4ap6a-nixops-1.6pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1033, in run_with_notify
f()
File "/nix/store/wm0jd92gb5vflky0bhkal5v9hvg4ap6a-nixops-1.6pre0_abcdef …
```
> [DEVOPS-687]  DD | disk_hydra: warning vs. critical threshold

- jobsets/default.nix
It would be good to have hydra building cardano-sl `release/1.1.0` branch so that it goes in the binary cache.
I haven't tested this change but it seems like it could work.
The [cardano-sl-1-0 jobset](https://hydra.iohk.io/jobset/serokell/cardano-sl-1-0#tabs-evaluations) doesn't seem to evaluate, possibly because the given branch doesn't exist in the repo.
> jobsets: Add cardano-sl-1-1

- iohk/UpdateLogic.hs
`daedalus/.travis.yml` was wrong. Since the failing download exits the program, just ignore travis and use buildkite instead.
> [DEVOPS-711] find-installers: Disable downloading from travis

- README.md
- default.nix
- scripts/ci.sh
- shell.nix
plain `nix-shell` gives you a shell with just `io`, `nixops`,and `terraform` and no cardano or ghc
`nix-shell -A ioSelfBuild` gives you a shell with `io` and `ghcid-io` functions and a ghc that can build iohk-ops
`nix-shell -A withAuxx` gives a shell with io, auxx, and tools, no ghc
> re-arrange shell.nix to add new features and improve perf

- README.md
This clarifies procedure for adding keys for access to devops infrastructure.
> docs: update documentation on procedure for adding ssh keys

- modules/hydra-master.nix
Instead, jobs are delegated to external build slaves.
> [DEVOPS-738] Prevent Hydra from running jobs on itself

- cardano-sl-src.json
`cardano-sl-src.json` was pointing to a commit on a PR branch, rather than a commit on `develop`.
> [DEVOPS-682] Update cardano-sl version to latest develop

- jobsets/default.nix
The branches have been renamed so that the repo is now git-flow compliant.
The new jobsets are:
* cardano-sl -- develop branch
* cardano-sl-master -- latest production release
* cardano-sl-1-0 -- 1.0.x branch
> hydra: Update cardano jobsets

- modules/cardano-service.nix
Because
https://github.com/input-output-hk/cardano-sl/pull/2716
and
https://github.com/input-output-hk/cardano-sl/commit/9ff4a9d40d246667cac84318f970e4523cef0e8c
removed --no-ntp switch from scripts.
> [PB-12] --no-ntp removed

- default.nix
- iohk/Appveyor.hs
- iohk/Cardano.hs
- iohk/NixOps.hs
- iohk/UpdateLogic.hs
- iohk/UpdateProposal.hs
- iohk/iohk-ops.hs
- shell.nix
This adds more automation for the update-proposal script.
* The inputs to the process are now Daedalus revision, block version, voter index. The other values are looked up from various places.
* Adds find-installers, upload-s3 subcommands under update-proposal. These are used to populate the update proposal work dir with necessary info. The standalone versions of these remain.
* Adds set-version-json which matches the current website format but also includes SHA256 hashes.
> [DEVOPS-709] Fix iohk-ops set-version-json and add sha256 hashes

- iohk/Appveyor.hs
- iohk/InstallerVersions.hs
- iohk/Nix.hs
- iohk/NixOps.hs
- iohk/Types.hs
- iohk/UpdateLogic.hs
- iohk/UpdateProposal.hs
- iohk/Utils.hs
- iohk/default.nix
- iohk/iohk-ops.cabal
- iohk/iohk-ops.hs
* Versions and commit ids are now found by using nix.
* It now supports downloading of both staging and mainnet installers (DEVOPS-690).
* iohk-ops find-installers now prints a handy summary when finished ([example](https://github.com/input-output-hk/internal-documentation/wiki/iohk-ops-reference#find-installers)).
* Actually downloading the files is now optional in iohk-ops find-installers.
* Moved s3upload command into subcommand of update-proposal.
* It should be fairly simple now to add Linux installer support (DEVOPS-13).
* Straightened out the data types a little bit.
* Split out the code related to getting Daedalus installer version info into its own module.
* Some churn with converting some values to FilePath type.
> [DEVOPS-806] Update find-installers version scheme

- deployments/cardano-nodes-env-production.nix
- deployments/cardano-nodes-env-staging.nix
- modules/datadog-monitors.nix
So far tested only by building the nixops network.
Can anyone suggest a good way of testing that doesn't involve deploying to staging?
> [DEVOPS-794] Add inodes monitor for mainnet and staging clusters

- scripts/find-all-revisions.sh
Apparently due to xargs, thanks to @365andreas for finding it.
https://stackoverflow.com/questions/26540813/got-exit-code-123-in-find-xargs-grep
This change also makes the grep run faster when executed locally in a dirty git checkout.
> [DEVOPS-833] buildkite CI: fix build failing with "exit status 123"

- modules/datadog-monitors.nix
Found the cause of "Warning threshold must be greater than critical with < comparison" error was my blindness. Now the monitor can actually be deployed.
> [DEVOPS-794] Fix inodes available monitor

- modules/hydra-master.nix
- modules/hydra-not-found.patch
this should prevent the 410 gone errors happening in CI
> patch hydra to return 404 instead of 410

- modules/common.nix
- modules/ntp_fix.nix
- modules/openat.patch
this continues ths fix from https://github.com/NixOS/nixpkgs/pull/24573
the above PR likely missed the `openat` syscall due to it not opening the drift compensation file for several hours
> [DEVOPS-881] fix NTP crashing due to openat syscall

- nixpkgs-src.json
Fix for dd-agent iostats errors is backported now.
> [DEVOPS-903] Bump nixpkgs to latest 18.03

- cardano-sl-src.json
Previous rev is a few commits behind and pretty much the same, except for the ChangeLog. But it's best to deploy the exact revision tagged with 1.2.0.
> [DEVOPS-903] Bump cardano-sl to 1.2.0 tagged version

- iohk/NixOps.hs
- iohk/UpdateLogic.hs
- iohk/UpdateProposal.hs
- iohk/Utils.hs
This recognises the `.bin` files on Buildkite as Linux installers.
It is no longer a fatal error if no installers are found for a certain CI system.
It doesn't include linux64 in the update proposal.
> [DEVOPS-788] Add support for finding Linux installers from CI

- deployments/infrastructure-env-production.nix
- modules/common.nix
- modules/deployer.nix
for an unknown reason, this reduces the memory usage of mainnet massively
> [DEVOPS-923] only install nixops on the deployer

- cardano-sl-src.json
- iohk/NixOps.hs
- iohk/UpdateProposal.hs
- iohk/iohk-ops.hs
- modules/cardano-service.nix
Using `cardano-sl.src` got broken after adding filtering of the sources.
See corresponding fix in input-output-hk/cardano-sl#3090.
> [DEVOPS-906] [DEVOPS-907] Update cardano-sl-src.json to release/1.3.0

- modules/hydra-master.nix
this PR configures hydra to upload all artifacts to the S3 bucket iohk-nix-cache
it relies on an IAM user that has S3 access to the bucket
and the access keyid/secret have to be configured in /var/lib/hydra/queue-runner/.aws/credentials
that can be automated with the following commands
```
sudo -u hydra-queue-runner -i
nix run nixpkgs.awscli
aws configure
```
the PR also handles redirections of binary-cache files from hydra.iohk.io to https://iohk-nix-cache.s3-eu-central-1.amazonaws.com
> [DEVOPS-836] configure hydra to upload everything to S3

- iohk/UpdateProposal.hs
The output of cardano-auxx seems to have changed slightly, and the code couldn't deal with it.
> [DEVOPS-938] update-proposal: fix parsing of cardano-auxx hash

- deployments/report-server-bucket-storage.nix
Have tested this with a slightly modified developer cluster.
```
nixops ssh -d devops-823 ssh report-server
dd if=/dev/zero bs=1M count=21 of=/var/lib/report-server/index.log
systemctl start logrotate
ls -l /var/lib/report-server
mv /var/lib/report-server/index.log-20180515.gz  /var/lib/report-server/index.log-20180514.gz
dd if=/dev/zero bs=1M count=21 of=/var/lib/report-server/index.log
systemctl start logrotate
ls -l /var/lib/report-server
```
Results:
```
[root@devops-823:~]# ls -l /var/lib/report-server/
total 48
-rw-r--r-- 1 report-server report-server 21397 May 15 08:53 index.log-20180514.gz
-rw-r--r-- 1 root          root          21397 May 15 08:55 index.log-20180515.gz
```
> [DEVOPS-823] report-server: rotate index.log every 20MB

- deployments/edgenodesv2.nix
- modules/cardano-benchmark.nix
```
nixops create -d edgenodes deployments/edgenodesv2.nix
nixops set-args -d edgenodes --argstr accessKeyId staging-key --arg nodes 1 --arg walletsPerNode 2 --arg topologyFile ./topology-stress-test.yaml --arg systemStart 1506450213 --argstr configKey mainnet_dryrun_full
```
and a topology file:
```
wallet:
fallbacks: 7
valency: 1
relays:
- - ip: 1.2.3.4
```
that is enough to spawn 2 wallets on 1 node in aws
> update the edgenode deployment to work with the new cardano

- iohk/Constants.hs
- iohk/iohk-ops.hs
It seems that 'develop' was abandoned ~120 commits ago, but the default
was not updated, which caused a confusing error due to config path
inconsistencies. 'master' seems to be the main branch, so I'm updating
accordingly.
> Change defaultIOPSBranch from 'develop' to 'master'

- jobsets/default.nix
1.3.0 is now merged to master and tagged. So change the Hydra jobset to follow the hotfix branch.
> [DEVOPS-998] Update Hydra jobset for 1.3.1

- deployments/security-groups.nix
- modules/cardano-explorer.nix
Enable acme and https for NGINX which proxies cardano-explorer.
This is required for putting explorer in an iframe on a HTTPS website.
Mainnet explorer can still use cloudflare.
> [DEVOPS-398] cardano-explorer: enable HTTPS

- iohk/UpdateProposal.hs
- iohk/common/Arch.hs
- iohk/common/NixOps.hs
- iohk/common/Types.hs
- iohk/common/UpdateLogic.hs
- iohk/common/Utils.hs
- iohk/iohk-ops.cabal
- iohk/test/UpdateProposalSpec.hs
* [DEVOPS-788](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-788)
- Adds support for proposing linux installers with `io update-proposal submit`.
- Add a basic test case for checking the `cardano-auxx propose-update` command line.
* [DEVOPS-868](https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-868)
- Pass tty to `gpg2` subprocess so that password entry works.
- Make `io update-proposal find-installers -u user-id` optional so that the default signing key from the keyring can be used.
- Move sha256 and blake2b hashing of installers earlier to the `find-installers` step.
> [DEVOPS-788] [DEVOPS-868] Update proposal Linux support and signing fix

- iohk/common/NixOps.hs
- iohk/common/Types.hs
- iohk/common/UpdateLogic.hs
- shell.nix
This fixes the unfortunate problem of `installer-uri-base` being required even in the cases where it's not needed.
> Fix config parsing

- .gitignore
- iohk/UpdateProposal.hs
- iohk/common/Arch.hs
- iohk/common/NixOps.hs
- iohk/common/UpdateLogic.hs
- iohk/iohk-ops.hs
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-868
* Makes the _date_ argument to `io update-proposal` commands compulsory to avoid problems running the procedure around UTC midnight.
* Roll the `generate` step into `submit`.
* Fix pattern matching of the update proposal ID which got broken by cardano-sl 1.3.0.
* Require a single CI build per commit. If there is more than one build found (e.g. due to multiple pull requests for the same revision), then the user has to provide a build number.
> [DEVOPS-868] Update proposal automation fixes

- iohk/iohk-ops.hs
- modules/hydra-master.nix
Adds grafana and influxdb to hydra master. Cleans up nginx to make it easier to work with in the future. grafana should have google oauth support, although untested as of yet.
> [DEVOPS-1039] add influxdb/grafana and clean up nginx config for hydra

- modules/hydra-extra-debug.patch
- modules/hydra-master.nix
this greatly increases how verbose hydra-notify is, to allow better debugging of when it happens to fail
> add more debug to hydra-notify and githubStatus

- modules/hydra-lowest.patch
- modules/hydra-master-common.nix
https://github.com/NixOS/hydra/commit/dc5e0b120aac06f1c46bcf0296d14775d72c2354#diff-fa352a753d5c2e84da9af5fa5e5f2e35R729
i believe the above commit, causes `hydra-queue-runner` to never load builds that are reusing a build# from a past eval
and as a result, it never runs the `hydra-notify` again for that build#, (which would notice its a member of a new eval and update properly)
removing the limitation on new builds should prevent the bug
> [DEVOPS-1033] potentially fix missing cached builds in github

- nix-darwin/modules/basics.nix
- nix-darwin/modules/double-builder-gc.nix
- nix-darwin/services/builder-gc.nix
The Nix min-free setting seems to be unreliable.
Add back GC at quarter-hour intervals.
Increase the minimum to 2000MB.
> [DEVOPS-1022] nix-darwin: Also do periodic GC

- bors.toml
- jobsets/default.nix
- modules/hydra-github-pr-filter.patch
To get hydra checks working with bors-ng in iohk-ops:
1. The CI status entries on GitHub must have the same name -- whether PR, staging branch, or master.
- So adjust our magic regexp to remove `bors-(staging|trying)` branch names from github status entries
- Adjust the iohk-nixops PR jobset names so that the magic regexp applies.
2. `bors.toml` must have the job names listed.
3. The `bors-staging` and `bors-trying` branches need to be built automatically by Hydra.
> [DEVOPS-1044] bors: Add hydra jobs to required checks

- bors.toml
- iohk/common/Constants.hs
- jobsets/default.nix
- jobsets/spec.json
- modules/hydra-master-main.nix
The repo used to be at this URL, but no longer: https://github.com/input-output-hk/iohk-nixops
This change will fix GitHub CI status updates for the master branch.
> [DEVOPS-1071] iohk-nixops → iohk-ops

- cardano-sl-src.json
Updates nixops deployments to use latest release/1.3.1.
Merge when ready to deploy on staging.
> [DEVOPS-998] Update cardano-sl to latest release/1.3.1

- iohk/common/CommandLineUtils.hs
- iohk/common/NixOps.hs
- iohk/iohk-ops.cabal
- iohk/iohk-ops.hs
Allows bash completion of options that are filenames/directories.
Needs #449 merged first so that it works properly.
I haven't made much attempt to clean up/refactor -- this can be done as part of DEVOPS-1066.
> [DEVOPS-1066] iohk-ops: add some bash filename completion

- nix-darwin/modules/double-builder-gc.nix
Due to the size of our builds, 2GB min-free is not enough to avoid running out of space.
> [DEVOPS-1078] nix-darwin: increase GC min-free to 6GB

- modules/buildkite-agent.nix
- nix-darwin/modules/buildkite-agent.nix
Provide git-lfs in the Buildkite environment so that LFS repos can be cloned from GitHub.
Set the NIX_PATH for the builds to be what's running on the buildkite-agent system. Mostly, our builds will be pinning the nixpkgs version, so this is usually irrelevant. But sometimes it's helpful to be able to use a nix package from the host system's package set. For example, docker.
> infra: Provide minimal build environment for buildkite-agent

- modules/hydra-master-main.nix
Mantis Hydra is submodule-capable.  Let's make our main Hydra as good.
> hydra-main:  use same commit as hydra-mantis

- deployments/cardano-faucet-env-testnet.nix
Tested by deploying on testnet, with datadog downtime enabled, with the warning threshold tweaked 100x.
> [DEVOPS-1123] testnet: Add monitor for faucet balance

- cardano-sl-src.json
This will allow us to deploy https://github.com/input-output-hk/cardano-report-server/pull/25
> [DEVOPS-1143]  bump cardano-sl for report-server

- iohk/iohk-ops.hs
Copy&paste error -- it was -r instead of -d.
> [DEVOPS-1141] io find-installers: fix --download short option

- jobsets/default.nix
- jobsets/spec.json
* Adds jobsets for the cardano-wallet repo.
* The file needed to be cleaned up because there was code duplication for every project.
Build the jobset spec with example data on the master branch and PR branch, then compare results with a diff program.
cat $(nix-build jobsets/default.nix --no-out-link) | jq . > spec.json
> [DEVOPS-1179] jobsets: Clean up and add jobset for cardano-wallet

- modules/hydra-master-main.nix
Updates the hydra config file.
The CI status will be picked up by the AppVeyor daedalus installers build.
> [DEVOPS-1208] hydra: send github CI status for daedalus-mingw32-pkg

- jobsets/default.nix
Tested with:
jq . < $(nix-build --no-out-link jobsets/default.nix)
See: input-output-hk/cardano-shell#11
> [DEVOPS-1120] jobsets: add cardano-shell

- modules/buildkite-agent.nix
Needed for input-output-hk/haskell.nix#56.
Before deploying, create these keys on the infra deployer:
```
ssh-keygen -t rsa -f static/buildkite-hackage-ssh -C buildkite-agent@hackage.nix
ssh-keygen -t rsa -f static/buildkite-stackage-ssh -C buildkite-agent@stackage.nix
```
After deploying, add these as deploy keys to the relevant github repos.
> infra: Add GitHub deploy keys to buildkite-agent

- jobsets/default.nix
- jobsets/spec.json
- modules/hydra-master-main.nix
See also: input-output-hk/haskell.nix#93
> jobsets: add haskell.nix

- modules/buildkite-agent.nix
Fix problems found when doing input-output-hk/haskell.nix#93.
> Buildkite: fix NIX_PATH and add deployment key for haskell.nix

- jobsets/default.nix
- jobsets/spec.json
- modules/hydra-master-main.nix
this initial PR configures hydra to report the `required` job on both the `Cardano` and `serokell` project
that will allow smoothly transitioning the required CI checks in each repo over
> [DEVOPS-1252] begin migration to the Cardano project in hydra

- modules/buildkite-agent.nix
It's failing with:
/nix/store/v61l5n40ivddx5p0xza87wyn92fgjwz2-buildkite-agent-hooks/environment: line 8: NIX_PATH: unbound variable
> Buildkite: Fix environment hook evaluation

- gac.sh
We were hardcoding the cluster components names in `gac.sh`. This could lead to some
issues if the cluster we're trying to deploy does not contains the
all the hardcoded components.
> [GAC] Extracting the actual cluster nodes in ALL_NODES

- deployments/packet-net.nix
This was a change required to redeploy buildkite to update an API token in a hook.
> packet.nix machine fix for manual being renamed

- modules/devops.nix
- modules/monitoring-exporters.nix
- modules/production.nix
- modules/staging.nix
- modules/testnet.nix
so that it can be used outside cardano specific deployments.
> Avoid reference on globals from monitoring-exporters.nix

- modules/deployer-base.nix
We need to override both the packages and the users installed on a downstream deployer.
> deployer-base: Making packages and users overridable.

- gac.sh
which I have erroneously broken while trying to satisfy Shellcheck
> Fix `gac genkey`

- modules/monitoring-services.nix
due to the systemd services `graylog-preload` being defined regardless of whether graylog is enabled or not (... which causes it to fail, crash and burn). I need to be able to deploy without graylog simply because graylog is currently out of scope for the PR I'm trying to merge (and I require some changes that were committed on top of the graylog changes).
> Fix not being able to disable graylog

- deployments/monitoring-env-production.nix
- deployments/monitoring-env-staging.nix
- deployments/monitoring-env-testnet.nix
- deployments/monitoring.nix
- lib.nix
- modules/graylog/graylogPreload.sh
- modules/monitoring-services.nix
- scripts/ci.sh
This commit cleans up the graylog and grafana static credentials,
making use of a new iohk-ops lib.nix function `makeCreds`.
Customizations for the monitoring server size in the testnet,
staging and production environments for larger EBS gp2 vols,
EC2 server type and boot loader block device type are added.
> Restruct mon creds, add svr sizing customization

- cardano-sl-src.json
- deployments/infrastructure-env-production.nix
- deployments/monitoring-aws.nix
- deployments/monitoring.nix
- iohk/iohk-ops.hs
- modules/monitoring-services.nix
- Remove security group redundancy in development clusters
- Disable deadmansnitch silently upon no static creds key (by setting pingUrl = null)
- Disable pagerduty silently upon no static creds file (by setting to a key of null)
- Bump cardano-sl pin to 3.0.1 tag
- Change io set-rev behavior to no commit by default
> Monitoring improvements

- modules/monitoring-exporters.nix
- modules/monitoring-services.nix
Upstream changes to `iohk-ops` have introduced an infinite recursion in `gac`-based deployments. This fixes it.
Kudos to @cleverca22 for the intense bisect session and to @johnalotoski for the moral support!
> Fix infinite recursion

- gac-new.sh
`gac new` is currently failing when used from within an overlay. 
We are now explicitly referring to the `iohk-ops` root directory.
> Fix gac-new when used in overlay mode

- gac.sh
... rather than a git submodule. i.e., don't assume that we are a subdirectory of
the consumer as would be the case when using a git submodule.
This *shouldn't* break submodule-based consumers.
> GAC: make it play nice with `iohk-ops` as a `niv` pin

- cardano-node-src.json
- default.nix
- shell.nix
1. Pull in `cardano-node` packages 
2. Add `cardano-node`'s binaries to the shell, including `genesis-tool`.
> shell:  include 'genesis-tool' from 'cardano-node'

- cardano-node-src.json
- config.nix
- modules/parameters.nix
Currently `config.nix` loads parameters from `modules/parameters.nix` and that
is hardcoded. As a result, repositories using GAC cannot declare their own
config parameters and must add those parameters here. This creates unnecessary
overhead/red-tape and is just not fun.
This:
1) changes the hydra parameter namespace from a nixos submodule to a regular
nested attrset; and
2) optionally loads `<local-module/parameters.nix>` if it exists.
Note that I'm still working on revisiting/simplifying the way this whole thing
works and this is just a (hopefully temporary) workaround to unblock my
hydra-notifications related work.
> GAC: Let consumers declare parameters

- gac.sh
while retaining backward compatibility with our current pin mechanism.
Niv sources are `{ outPath = ... }` objects while oldschool pins are
"strings" (or ./paths? doesn't really matter).
I tested with both Niv and regular pins.
----
#
> Feature: Support Niv sources in `gac`

- modules/hydra-master-main.nix
by default, postgresql allows 100 connections max
but hydra will keep the last 128 connections in a pool, causing problems
> reduce the default pool size for postgresql connections

- gac.sh
I just had an issue with the monitoring instance of a cluster and
tried to `gac destroy --include monitoring`, fully expecting it to
behave like `gac deploy` (... or `nixops destroy`). To my horror, it
went ahead and nuked the entire cluster, automatically answering ‘yes’
to all the "ARE YOU SURE?!?!" prompts. Fortunately, this was just a
test cluster so nothing too bad happened. Upon looking at the code I
learned that:
1. `gac` clumps together `nixops destroy` and `nixops delete` under
multiple aliases (including, but not limited to `gac destroy` and
`gac delete`).
2. `gac destroy` passes the `--confirm` flag to `nixops destroy` which
means that it will not stop to ask the user if they’re sure; and
3. The arguments passed to `gac destroy` aren’t relayed to `nixops
destroy` (or `nixops …
> Make gac less dangerous

- default.nix
this removes over 2gig from the closure of the `iohk-ops` build
> reduce closure size of iohk-ops

- modules/buildkite-agent-container.nix
Temporary modification to packet-buildkite-1 until we migrate to reduce
container count by 1 and priority since this server has half the capacity of
the others and is experiencing storage pressure.
Changes made by others in the team that had to be stashed due to clashes with PR #702 and I'm now pushing back up to master.
@iohk-devops
> Reduce container count to reduce storage pressure

- jobsets/default.nix
This adds options for controlling the jobset size based on whether the Hydra build is for Bors or is a PR branch build.
This is useful to control CI load, since some test suites take 20-30 minutes to execute and don't need to be run on every commit on a PR branch.
* Adds a "borsBuild" string argument to the bors jobsets so that projects can build different jobs under Bors.
For example, cardano-wallet could skip running the integration test suite unless the build is for Bors.
The possible values of the "borsBuild" argument (if present) are "trying" and "staging".
* Adds a "pr" string argument to the GitHub PR jobsets. The value is the PR number.
Tested with:
jq . < $(nix-build --no-out-link jobsets/default.nix)
After merging this, we need to monitor Hydra to check that evaluation is not …
> Jobsets: Add borsBuild and pr input arguments
